# Generated by Django 2.1.5 on 2019-01-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_migrate_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='representative_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='representative_name',
        ),
    ]
